openapi: 3.0.3
info:
  title: African Market OS — Minimum Viable Relationships (MVR) API
  version: 2.5.1
  description: >
    The MVR API measures trust, belonging, permission, and embeddedness to determine
    relational readiness for ventures and initiatives entering high-context markets.
  x-origin:
    - url: https://africanmarketos.com/openapi_mvr_api_v1.yaml
      format: openapi
      version: "3.0"
